### ISSUE TITLE
Athenaeum spams debugging console logs for cover calculations.

### ISSUE THREAD

**Issue by thatlonelybugbear** [vtt-lair/simbuls-athenaeum#2]
From a quick glance at the code, it seems that the game settings for debug being true or false are never checked in `logger.js`

As I am not sure if this is intended behaviour or not and what I did makes sense, I will add it here as an issue and not 2 separate PRs (here and Cover Calculator)
```js
export class logger {
    static info(title, ...args) {
        console.log(`${title || "" }  | `, ...args);
    }
  
    static debug(isDebug, ...args) {
        if (game.settings.get(isDebug,"debug")) {
            this.info("DEBUG | ",isDebug, ...args);
        }
    }

    static error(title, ...args) {
        console.error(`${title || "" } | ERROR | `, ...args);
        ui.notifications.error(`${title || "" } | ERROR | ${args[0]}`);
    }

    static notify(...args) {
        ui.notifications.notify(`${args[0]}`);
    }
}
```
The initial relevant code was 
```js
static debug(isDebug, ...args) {
        if (isDebug) {
            this.info("DEBUG | ", ...args);
        }
    }
 ```
 
 
 That needed 2 secondary small changes in `Simbul's Cover Calculator` and specifically in `CoverCalculator.js:665` 
```js
   logger.debug(MODULE.data.name,"Collisions | ", collisions);
   logger.debug(MODULE.data.name,"Results | ", results);
 ``` 
 and in `Shape.js:77` 
```js
   logger.debug(MODULE.data.name,'Ignoring invalid wall:', wall);
```

**Comment by vtt-lair** [comment]
Thanks for the detailed information. This is what happens when you split a big module into smaller ones. I'll update this in all relevant modules later this week, once I have some time to give love to all the modules :)

**Comment by MotoMoto1234** [comment]
This is exactly my issue over in cover calculator I was just a dunce and put it in the wrong modules github sorry bout that.

**Comment by vtt-lair** [comment]
This will be fixed in the next release of the modules
