### ISSUE TITLE
Simbul's Athenaeum is auto-downloading "Simbul's Cover Calculator" when I update it.

### ISSUE THREAD

**Issue by GambetTV** [vtt-lair/simbuls-athenaeum#4]
Not sure why this is happening, but if I update this module, it is automatically downloading your Cover Calculator module, without asking me if I want it. I only use Creature Aide, so I don't know why I need this one.

**Comment by vtt-lair** [comment]
That is weird. Athenaeum is setup as a requirement for Cover Calculator and not the other way around. It's definitely not supposed to do that.

**Comment by vtt-lair** [comment]
Ooook... for some reason the json file in the release is the Cover Calculator one. Let me fix the release

**Comment by vtt-lair** [comment]
I've created a new release so that the module json file is the correct one. Please update to 1.0.7 and it should no longer download Cover Calculator. Thanks for pointing this out!
